// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web2.API.Data;

#nullable disable

namespace Web2.API.Migrations
{
    [DbContext(typeof(TP2A_Context))]
    [Migration("20230828021633_DeleteCascade")]
    partial class DeleteCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web2.API.Data.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Web2.API.Data.Models.Evenement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CategorieID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCategorie")
                        .HasColumnType("integer");

                    b.Property<string>("Organisateur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Prix")
                        .HasColumnType("double precision");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VilleID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CategorieID");

                    b.HasIndex("VilleID");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("Web2.API.Data.Models.Participation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvenementID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NombrePlace")
                        .HasColumnType("integer");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("EvenementID");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("Web2.API.Data.Models.Ville", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Villes");
                });

            modelBuilder.Entity("Web2.API.Data.Models.Evenement", b =>
                {
                    b.HasOne("Web2.API.Data.Models.Categorie", null)
                        .WithMany("Evenements")
                        .HasForeignKey("CategorieID");

                    b.HasOne("Web2.API.Data.Models.Ville", null)
                        .WithMany("Evenements")
                        .HasForeignKey("VilleID");
                });

            modelBuilder.Entity("Web2.API.Data.Models.Participation", b =>
                {
                    b.HasOne("Web2.API.Data.Models.Evenement", "Evenement")
                        .WithMany("Participations")
                        .HasForeignKey("EvenementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("Web2.API.Data.Models.Categorie", b =>
                {
                    b.Navigation("Evenements");
                });

            modelBuilder.Entity("Web2.API.Data.Models.Evenement", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Web2.API.Data.Models.Ville", b =>
                {
                    b.Navigation("Evenements");
                });
#pragma warning restore 612, 618
        }
    }
}
